// Checked-in mapping from GrowthZone member/directory category strings → app
// directory categories (E16 roster import). Keys are compared
// case-insensitively after trimming, same contract as qwick-category-map.
//
// PROVENANCE CAVEAT: seeded from typical chamber-of-commerce category
// vocabulary (GrowthZone tenants name their own categories) BEFORE the first
// real export was seen. The importer's preflight report lists every distinct
// unmapped category string it meets with a count — extending this map from
// that list is a data edit, not a code change. Unknown strings map to
// 'other' and the raw values are preserved verbatim on the record's
// `sourceCategories`.

import type { DirectoryCategory } from "../schemas/directory";

const MAP: Record<string, DirectoryCategory> = {
  // eat
  restaurants: "eat",
  restaurant: "eat",
  "restaurants & food": "eat",
  dining: "eat",
  food: "eat",
  "food & beverage": "eat",
  "food & drink": "eat",
  "food service": "eat",
  catering: "eat",
  caterers: "eat",
  cafes: "eat",
  cafe: "eat",
  coffee: "eat",
  "coffee & tea": "eat",
  "coffee shop": "eat",
  bakery: "eat",
  bakeries: "eat",
  bars: "eat",
  "bars & pubs": "eat",
  pubs: "eat",
  breweries: "eat",
  brewery: "eat",
  pizza: "eat",
  seafood: "eat",
  "ice cream": "eat",
  wineries: "eat",
  winery: "eat",
  distillery: "eat",
  // stay
  lodging: "stay",
  accommodations: "stay",
  accommodation: "stay",
  hotels: "stay",
  hotel: "stay",
  "hotels & motels": "stay",
  motels: "stay",
  "bed & breakfast": "stay",
  "bed and breakfast": "stay",
  inn: "stay",
  inns: "stay",
  camping: "stay",
  campgrounds: "stay",
  rv: "stay",
  "rv parks": "stay",
  "vacation rentals": "stay",
  "vacation rental": "stay",
  // shop
  shopping: "shop",
  shop: "shop",
  retail: "shop",
  "retail shops": "shop",
  "retail & specialty": "shop",
  gifts: "shop",
  "gift shop": "shop",
  "gifts & specialty": "shop",
  galleries: "shop",
  "art gallery": "shop",
  antiques: "shop",
  books: "shop",
  bookstore: "shop",
  grocery: "shop",
  "grocery & convenience": "shop",
  florist: "shop",
  florists: "shop",
  jewelry: "shop",
  clothing: "shop",
  boutique: "shop",
  "farm & garden": "shop",
  nursery: "shop",
  "thrift & consignment": "shop",
  // services
  services: "services",
  "professional services": "services",
  "business services": "services",
  "business & professional": "services",
  "business & professional services": "services",
  health: "services",
  "health & wellness": "services",
  "health & medical": "services",
  "health care": "services",
  healthcare: "services",
  medical: "services",
  dental: "services",
  dentists: "services",
  chiropractic: "services",
  veterinary: "services",
  "pet services": "services",
  pets: "services",
  finance: "services",
  financial: "services",
  "financial services": "services",
  banking: "services",
  banks: "services",
  "banks & credit unions": "services",
  "credit unions": "services",
  accounting: "services",
  accountants: "services",
  "tax services": "services",
  "real estate": "services",
  realtors: "services",
  "property management": "services",
  "title & escrow": "services",
  automotive: "services",
  "auto repair": "services",
  "auto services": "services",
  construction: "services",
  contractors: "services",
  "construction & contractors": "services",
  "home improvement": "services",
  "home services": "services",
  "home & garden": "services",
  landscaping: "services",
  plumbing: "services",
  electrical: "services",
  hvac: "services",
  legal: "services",
  attorneys: "services",
  "legal services": "services",
  insurance: "services",
  salon: "services",
  salons: "services",
  "salons & spas": "services",
  spa: "services",
  "beauty & spa": "services",
  barber: "services",
  "personal care": "services",
  "personal services": "services",
  storage: "services",
  "self storage": "services",
  printing: "services",
  marketing: "services",
  "marketing & media": "services",
  media: "services",
  technology: "services",
  "computer & it": "services",
  it: "services",
  consulting: "services",
  consultants: "services",
  photography: "services",
  photographers: "services",
  transportation: "services",
  "moving & storage": "services",
  utilities: "services",
  "funeral services": "services",
  childcare: "services",
  "child care": "services",
  cleaning: "services",
  "cleaning services": "services",
  // activities
  activities: "activities",
  recreation: "activities",
  "recreation & fitness": "activities",
  attractions: "activities",
  tours: "activities",
  "tours & charters": "activities",
  charters: "activities",
  "fishing charters": "activities",
  outdoors: "activities",
  "outdoor recreation": "activities",
  parks: "activities",
  arts: "activities",
  "arts & culture": "activities",
  "arts & entertainment": "activities",
  entertainment: "activities",
  events: "activities",
  "event venues": "activities",
  "event planning": "activities",
  "wedding & event services": "activities",
  fitness: "activities",
  "gyms & fitness": "activities",
  yoga: "activities",
  golf: "activities",
  marina: "activities",
  marinas: "activities",
  boating: "activities",
  "sports & recreation": "activities",
  theater: "activities",
  museums: "activities",
  // community
  community: "community",
  "community organizations": "community",
  "community services": "community",
  nonprofit: "community",
  "non-profit": "community",
  nonprofits: "community",
  "non-profit organizations": "community",
  "nonprofit organizations": "community",
  "civic & community": "community",
  "civic organizations": "community",
  churches: "community",
  "churches & religious organizations": "community",
  religious: "community",
  "religious organizations": "community",
  education: "community",
  schools: "community",
  "schools & education": "community",
  government: "community",
  "government & public services": "community",
  library: "community",
  "senior services": "community",
  "youth organizations": "community",
  "service clubs": "community",
  "chambers of commerce": "community",
};

/** Map upstream category strings to ONE app category: the first string with
 *  a known mapping wins; no known strings → 'other'. */
export function mapGrowthZoneCategories(raw: string[]): DirectoryCategory {
  for (const s of raw) {
    const hit = MAP[s.trim().toLowerCase()];
    if (hit) return hit;
  }
  return "other";
}

/** Preflight helper: the subset of `raw` with no mapping, for the run report
 *  (each is a candidate key to add to MAP above). */
export function unmappedGrowthZoneCategories(raw: string[]): string[] {
  return raw.filter((s) => !MAP[s.trim().toLowerCase()]);
}
