"use client";

// Interactive Leaflet map of Kingston parking: color-coded street overlay
// (every public street in the UGA), zone polygons/markers, ATMs, and the
// UGA boundary. Leaflet touches `window` at module scope, so it is imported
// dynamically inside useEffect — this component renders an empty shell on
// the server and hydrates on the client. Leaflet CSS is global.
//
// Street geometry lives in /geo/street-parking.json (generated by
// scripts/gen-street-parking.py from OSM + the Census Kingston CDP boundary)
// and is fetched at runtime so the JS bundle stays lean.
//
// Street View: every popup gets a free deep link (no API key). If
// NEXT_PUBLIC_GMAPS_EMBED_KEY is set, clicking a feature also opens an
// embedded Street View panel below the map (Maps Embed API — free tier).
//
// Default Leaflet marker icons are deliberately NOT used (their asset paths
// break under bundlers). Colors here are intentionally hex — they live on
// the map canvas, not in the page's token system.

import { useEffect, useRef, useState } from "react";
import type { Map as LeafletMap } from "leaflet";
import type { MapZone, ParkingRule } from "@/lib/data/parking";
import type { Atm } from "@/lib/types";

const RULE_COLORS: Record<ParkingRule, string> = {
  "free-2hr": "#2e9e4f",
  "free-unrestricted": "#1E96C0",
  paid: "#7c4dbe",
  "park-and-ride-24h": "#e8891d",
  prohibited: "#d43d3d",
};

type StreetRule = "free-2hr" | "free-unrestricted" | "prohibited" | "default";

const STREET_COLORS: Record<StreetRule, string> = {
  "free-2hr": "#2e9e4f",
  "free-unrestricted": "#1E96C0",
  prohibited: "#d43d3d",
  default: "#8b9aa8",
};

const STREET_RULE_LABELS: Record<StreetRule, string> = {
  "free-2hr": "Free street parking · 2-hour limit",
  "free-unrestricted": "Free street parking · no time limit",
  prohibited: "No street parking",
  default: "No known restriction — free where unsigned",
};

const ATM_COLOR = "#16405e"; // dark navy
const BOUNDARY_COLOR = "#324A6D";

interface StreetSegment {
  name: string;
  rule: StreetRule;
  coords: [number, number][];
  note?: string;
}

interface StreetData {
  boundary: [number, number][];
  segments: StreetSegment[];
}

const EMBED_KEY = process.env.NEXT_PUBLIC_GMAPS_EMBED_KEY;

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function overnightLine(zone: MapZone): string {
  if (zone.overnight === "yes") return "Overnight: OK";
  if (zone.overnight === "no") return "Overnight: No";
  return zone.id.startsWith("port-")
    ? "Overnight: Call the Port office first — 360-297-3545"
    : "Overnight: Confirm on-site first";
}

function directionsUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=driving`;
}

/** Free Google Street View deep link — opens the panorama nearest the point. */
function streetViewUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/@?api=1&map_action=pano&viewpoint=${lat},${lng}`;
}

function linksRow(lat: number, lng: number, sourceUrl?: string): string {
  const links = [
    `<a href="${esc(streetViewUrl(lat, lng))}" target="_blank" rel="noopener noreferrer">👁 Street View</a>`,
    `<a href="${esc(directionsUrl(lat, lng))}" target="_blank" rel="noopener noreferrer">Directions</a>`,
  ];
  if (sourceUrl) {
    links.push(`<a href="${esc(sourceUrl)}" target="_blank" rel="noopener noreferrer">Source</a>`);
  }
  return `<p style="margin:6px 0 0;">${links.join(" · ")}</p>`;
}

function zonePopupHtml(zone: MapZone): string {
  const parts: string[] = [
    `<p style="margin:0;font-weight:600;font-size:0.95rem;">${esc(zone.name)}</p>`,
    `<p style="margin:4px 0 0;">${esc(zone.summary)}</p>`,
    `<p style="margin:4px 0 0;font-weight:600;">${esc(overnightLine(zone))}</p>`,
  ];
  if (zone.confidence !== "verified") {
    parts.push(
      `<p style="margin:4px 0 0;font-style:italic;">${esc(
        zone.sourceNote ?? "Per 2015 county study — obey posted signs."
      )}</p>`
    );
  }
  parts.push(linksRow(zone.center[0], zone.center[1], zone.sourceUrl));
  return `<div style="font-size:0.8rem;line-height:1.35;max-width:230px;">${parts.join("")}</div>`;
}

function streetPopupHtml(seg: StreetSegment): string {
  const mid = seg.coords[Math.floor(seg.coords.length / 2)];
  const parts: string[] = [
    `<p style="margin:0;font-weight:600;font-size:0.95rem;">${esc(seg.name)}</p>`,
    `<p style="margin:4px 0 0;font-weight:600;color:${STREET_COLORS[seg.rule]};">${esc(
      STREET_RULE_LABELS[seg.rule]
    )}</p>`,
  ];
  if (seg.note) {
    parts.push(`<p style="margin:4px 0 0;">${esc(seg.note)}</p>`);
  }
  if (seg.rule === "default") {
    parts.push(
      `<p style="margin:4px 0 0;font-style:italic;">Not field-surveyed — the sign on the pole always wins. State law tows vehicles left over 24 hours (RCW 46.55.085).</p>`
    );
  }
  parts.push(linksRow(mid[0], mid[1]));
  return `<div style="font-size:0.8rem;line-height:1.35;max-width:230px;">${parts.join("")}</div>`;
}

function atmPopupHtml(atm: Atm): string {
  const parts: string[] = [
    `<p style="margin:0;font-weight:600;font-size:0.95rem;">💵 ${esc(atm.name)}</p>`,
    `<p style="margin:4px 0 0;">${esc(atm.address)}</p>`,
    `<p style="margin:4px 0 0;">${esc(atm.feeNote)}</p>`,
    linksRow(atm.lat, atm.lng),
  ];
  return `<div style="font-size:0.8rem;line-height:1.35;max-width:230px;">${parts.join("")}</div>`;
}

interface SelectedSpot {
  name: string;
  lat: number;
  lng: number;
}

export function TownMap({
  zones = [],
  atms = [],
  showStreets = true,
  height = "460px",
  center = [47.7985, -122.4975],
  zoom = 15,
}: {
  zones?: MapZone[];
  atms?: Atm[];
  showStreets?: boolean;
  height?: string;
  center?: [number, number];
  zoom?: number;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<LeafletMap | null>(null);
  const [selected, setSelected] = useState<SelectedSpot | null>(null);

  useEffect(() => {
    let cancelled = false;

    (async () => {
      const L = (await import("leaflet")).default;
      // Guard: unmounted while loading, or already initialized (StrictMode).
      if (cancelled || !containerRef.current || mapRef.current) return;

      const map = L.map(containerRef.current, {
        center,
        zoom,
        scrollWheelZoom: false, // don't hijack page scroll; pinch/±-buttons still zoom
      });
      mapRef.current = map;

      L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png", {
        maxZoom: 19,
        attribution:
          '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
      }).addTo(map);

      // Street overlay + UGA boundary (fetched so the bundle stays lean).
      if (showStreets) {
        try {
          const res = await fetch("/geo/street-parking.json");
          if (res.ok && !cancelled && mapRef.current) {
            const data = (await res.json()) as StreetData;

            L.polygon(data.boundary, {
              color: BOUNDARY_COLOR,
              weight: 2,
              dashArray: "6 6",
              fill: false,
              interactive: false,
            }).addTo(map);

            // Draw "default" streets first so rule-bearing streets sit on top.
            const ordered = [...data.segments].sort(
              (a, b) => (a.rule === "default" ? 0 : 1) - (b.rule === "default" ? 0 : 1)
            );
            for (const seg of ordered) {
              const known = seg.rule !== "default";
              const mid = seg.coords[Math.floor(seg.coords.length / 2)];
              L.polyline(seg.coords, {
                color: STREET_COLORS[seg.rule],
                weight: known ? 6 : 3,
                opacity: known ? 0.85 : 0.5,
              })
                .addTo(map)
                .bindPopup(streetPopupHtml(seg), { maxWidth: 260 })
                .on("click", () => setSelected({ name: seg.name, lat: mid[0], lng: mid[1] }));
            }
          }
        } catch {
          // Overlay is progressive enhancement — the base map still works.
        }
      }

      for (const zone of zones) {
        const color = RULE_COLORS[zone.rule];
        const popup = zonePopupHtml(zone);
        const select = () =>
          setSelected({ name: zone.name, lat: zone.center[0], lng: zone.center[1] });
        if (zone.polygon && zone.polygon.length >= 3) {
          L.polygon(zone.polygon, {
            color,
            weight: 2,
            fillColor: color,
            fillOpacity: 0.35,
          })
            .addTo(map)
            .bindPopup(popup, { maxWidth: 260 })
            .on("click", select);
          // A polygon this small is a fiddly tap target on a phone — add a
          // matching center marker as well.
          L.circleMarker(zone.center, {
            radius: 7,
            color,
            weight: 2,
            fillColor: color,
            fillOpacity: 0.9,
          })
            .addTo(map)
            .bindPopup(popup, { maxWidth: 260 })
            .on("click", select);
        } else {
          L.circleMarker(zone.center, {
            radius: 9,
            color,
            weight: 2,
            fillColor: color,
            fillOpacity: zone.rule === "prohibited" ? 0.55 : 0.8,
          })
            .addTo(map)
            .bindPopup(popup, { maxWidth: 260 })
            .on("click", select);
        }
      }

      for (const atm of atms) {
        L.circleMarker([atm.lat, atm.lng], {
          radius: 6,
          color: "#ffffff",
          weight: 2,
          fillColor: ATM_COLOR,
          fillOpacity: 1,
        })
          .addTo(map)
          .bindTooltip(`💵 ${atm.name}`, { direction: "top", offset: [0, -6] })
          .bindPopup(atmPopupHtml(atm), { maxWidth: 260 })
          .on("click", () => setSelected({ name: atm.name, lat: atm.lat, lng: atm.lng }));
      }
    })();

    return () => {
      cancelled = true;
      mapRef.current?.remove();
      mapRef.current = null;
    };
    // Data arrays and view options are static page data; re-running the effect
    // would tear the map down mid-interaction.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div>
      <div
        ref={containerRef}
        style={{ height }}
        className="relative z-0 w-full overflow-hidden rounded-2xl border border-sand"
        role="region"
        aria-label="Map of Kingston street parking rules, lots, and ATMs"
      />
      {EMBED_KEY && selected && (
        <div className="mt-3 overflow-hidden rounded-2xl border border-sand">
          <div className="flex items-center justify-between bg-white px-4 py-2">
            <p className="text-sm font-semibold text-sound-deep">
              👁 Street View: {selected.name}
            </p>
            <button
              onClick={() => setSelected(null)}
              className="text-sm text-ink-soft hover:text-ink"
              aria-label="Close Street View"
            >
              ✕
            </button>
          </div>
          <iframe
            title={`Street View of ${selected.name}`}
            src={`https://www.google.com/maps/embed/v1/streetview?key=${EMBED_KEY}&location=${selected.lat},${selected.lng}&fov=90`}
            className="h-72 w-full border-0"
            loading="lazy"
            referrerPolicy="no-referrer-when-downgrade"
            allowFullScreen
          />
        </div>
      )}
      {!EMBED_KEY && selected && (
        <p className="mt-2 text-sm text-ink-soft">
          👁{" "}
          <a
            href={streetViewUrl(selected.lat, selected.lng)}
            target="_blank"
            rel="noopener noreferrer"
            className="font-medium text-tide-deep underline decoration-seaglass underline-offset-2"
          >
            Open Street View of {selected.name}
          </a>{" "}
          to see what the parking looks like.
        </p>
      )}
    </div>
  );
}

/** Color key for the map — render as a sibling right under <TownMap />. */
export function MapLegend({ showAtms = true }: { showAtms?: boolean }) {
  const zoneEntries: { color: string; label: string }[] = [
    { color: RULE_COLORS.paid, label: "Paid lot" },
    { color: RULE_COLORS["park-and-ride-24h"], label: "Park & ride · 24 hr" },
  ];
  const streetEntries: { color: string; label: string }[] = [
    { color: STREET_COLORS["free-2hr"], label: "Street: free, 2-hr" },
    { color: STREET_COLORS["free-unrestricted"], label: "Street: free, no limit" },
    { color: STREET_COLORS.prohibited, label: "Street: no parking" },
    { color: STREET_COLORS.default, label: "Street: no known limit" },
  ];
  return (
    <ul className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm text-ink-soft">
      {streetEntries.map(({ color, label }) => (
        <li key={label} className="flex items-center gap-1.5">
          <span
            aria-hidden
            className="inline-block h-1 w-5 rounded-full"
            style={{ backgroundColor: color }}
          />
          {label}
        </li>
      ))}
      {zoneEntries.map(({ color, label }) => (
        <li key={label} className="flex items-center gap-1.5">
          <span
            aria-hidden
            className="inline-block h-3 w-3 rounded-full"
            style={{ backgroundColor: color }}
          />
          {label}
        </li>
      ))}
      <li className="flex items-center gap-1.5">
        <span
          aria-hidden
          className="inline-block h-0 w-5 border-t-2 border-dashed"
          style={{ borderColor: BOUNDARY_COLOR }}
        />
        Kingston UGA
      </li>
      {showAtms && (
        <li className="flex items-center gap-1.5">
          <span
            aria-hidden
            className="inline-block h-3 w-3 rounded-full ring-2 ring-white"
            style={{ backgroundColor: ATM_COLOR }}
          />
          ATM
        </li>
      )}
      <li className="w-full text-xs text-ink-soft/80">
        Tap any street or lot for rules and a Street View peek at the actual curb.
      </li>
    </ul>
  );
}
