// Kingston parking — rewritten from research verified July 2, 2026 against:
//   Port of Kingston live parking page: https://portofkingston.org/port-of-kingston-parking/
//   Port 2025 Parking Policy PDF + official parking map dated 12-30-25
//     (POKPARK / POKHILL / POKTT text-to-pay zones, 25023 short code)
//   WSDOT Kingston terminal page (Diamond lot D515, 73 stalls, $8/$12 + multi-day rates)
//   Diamond PermitPoint: monthly permit $122.70 as of 2026-08-01 (WSDOT's $100 figure is stale)
//   Kitsap Transit park & ride list (George's Corner, Bayside Community Church)
//   Kitsap County Complete Streets Transportation Report (Heffron, May 2016 — the only
//     public per-street source; its curb inventory dates to 2015, so every street entry
//     below is "probable" and labeled "per 2015 county study — obey posted signs")
//   KCC 46.02/46.04 + RCW 46.55.085 (no county overnight ban; 24-hr abandoned-vehicle rule)
//
// IMPORTANT corrections baked in (they override earlier drafts):
//   - Overnight in Port numbered spaces is PROBABLE, not confirmed — the Port never
//     explicitly authorizes it for cars. Publish "call the Port office first: 360-297-3545".
//   - No RV parking on Port property, period (per the Port's live website — stricter
//     than the policy PDF; we publish the conservative version).
//   - The free 2-hour row is ~30 stalls (schematic count), not 40.
//   - The free 2-hour row sits beside Mike Wallace Park's NW corner — an earlier
//     draft placed it ~70 m NE at the Washington Blvd/SR-104 fork by Kiwanis
//     Park (the wrong park). The polygon below is the corrected location.
//   - Pennsylvania Ave is unrestricted on ONE SIDE ONLY; the other side is no-parking.
//   - Diamond D515 is 73 stalls per WSF (Parkopedia says 71).
//
// Port section polygons (July 2, 2026): georeferenced from the Port's official
// 12-30-25 schematic map, then snapped per-zone to Esri World Imagery aerials
// (±5–10 m — the schematic's similarity-fit residuals grow to ~15 m at the map
// edges, hence the per-zone snapping). All Port geometry is "probable" and
// deliberately hand-adjustable — a Chamber admin can drag any shape or pin to
// reality at /admin/map (edits overlay this seed via the "parking-zones" JSON
// store). Not polygonized: disabled stalls, the 3 employee stalls, Port-use
// stalls, and the small tenant caps at the SE ends of fan rows 19–88 and 1–4.
//
// The Port revises rates and Diamond reprices permits — re-verify quarterly.
//
// Street zones (E31 phase 6): each street entry carries `streetPaths` — the
// street's centre-line polyline(s), lifted verbatim from the app's own
// OSM-derived overlay (public/geo/street-parking.json, regenerated by
// scripts/gen-street-parking.py) and chained where OSM splits a street into
// consecutive ways. The map draws them as curb-hugging offset strokes.
// `curb` says WHICH side(s) of the street the rule is known to apply to; it is
// set ONLY where a source states the side explicitly (honesty rule — today
// that is Washington Blvd between the SR 104 legs, "both sides", Chamber
// field-verified July 2026). Unset curb = side unknown → the map draws one
// centre-line stroke and claims nothing about sides. Pennsylvania Ave is
// deliberately unset: the county study says ONE side only but not which one.

/* ------------------------------------------------------------------ */
/* Rich map dataset (used by the town map + parking page)              */
/* ------------------------------------------------------------------ */

export type ParkingRule =
  | "free-2hr"
  | "free-unrestricted"
  | "paid"
  | "business-customer"
  | "park-and-ride-24h"
  | "prohibited"
  | "load-zone"
  | "permit";

/**
 * Which curb(s) of a street a rule applies to. Compass sides, matching how
 * sources state it ("parking on the east side"). Only meaningful together
 * with `streetPaths`; unset = side unknown → render the centre line only.
 */
export type CurbSide = "both" | "east" | "west" | "north" | "south";

export const CURB_SIDES: CurbSide[] = ["both", "east", "west", "north", "south"];

/**
 * Who actually takes the money for a lot. We integrate with none of them — the
 * app hands the visitor off to the rail the operator already runs.
 */
export type PayVendor = "t2" | "parkmobile" | "paybyphone";

/**
 * One way to pay for a lot.
 *
 * SEED DEFAULTS ONLY. The Port revises codes and Diamond reprices, and the
 * research note in docs/PARKING-PAY-LINKS.md flags every value here as
 * verify-before-relying — so these are editable in /admin/map and the merged
 * store is the source of truth, never this file.
 */
export interface PayHandoff {
  vendor: PayVendor;
  /** T2 keyword ("POKHILL") or a ParkMobile/PayByPhone numeric zone. */
  code: string;
  /** T2 short code, e.g. "25023". Omitted for app/web vendors. */
  shortCode?: string;
  /** Button label override, e.g. "Pay with ParkMobile". */
  label?: string;
}

/**
 * The Port's lot-wide "see other lots" keyword, from the PAY HERE sign
 * photographed at the lot on 2026-08-06 ("To See Other Lots, Text PARKATPOK To
 * 25023"). Not a zone code — it lists every Port lot rather than starting a
 * session, which is why it is a constant here and not a PayHandoff on any zone.
 */
export const PORT_LOT_INDEX_CODE = "PARKATPOK";
export const PORT_SHORT_CODE = "25023";

export interface MapZone {
  id: string;
  name: string;
  rule: ParkingRule;
  /** One-line gist shown in popups and card headers. */
  summary: string;
  /** Longer prose for cards. */
  details: string;
  confidence: "verified" | "probable" | "unverified";
  sourceUrl?: string;
  /** Caveat surfaced whenever confidence is not "verified". */
  sourceNote?: string;
  overnight: "yes" | "no" | "confirm-first";
  /** [lat, lng] */
  center: [number, number];
  /** Optional outline for lots/rows with known corner coordinates. */
  polygon?: [number, number][];
  /**
   * Street centre-line geometry: one or more [lat, lng] polylines (a street
   * OSM splits into disjoint stretches keeps them separate — never bridge a
   * gap the source doesn't claim). When set, the zone renders as curb-hugging
   * offset strokes instead of a polygon/pin. Seed values come verbatim from
   * public/geo/street-parking.json.
   */
  streetPaths?: [number, number][][];
  /** See CurbSide. SEED VALUES ONLY WHERE A SOURCE NAMES THE SIDE. */
  curb?: CurbSide;
  /**
   * Photos of the lot, as SHARED MEDIA LIBRARY names ("<sha1>.jpg" — see
   * src/lib/media/refs.ts), newest-first order chosen by the admin.
   *
   * The library rather than a parking-specific upload path, deliberately: it
   * already content-addresses the bytes, strips EXIF (a phone photo of a lot
   * carries GPS), and holds the alt text and credit next to the image, which is
   * exactly what a popup needs and what a bare filename cannot give. A photo of
   * the pay station reused on a listing page is then genuinely one object.
   *
   * Seed zones ship without photos: the Chamber takes these on the ground.
   */
  images?: string[];
  /**
   * How to pay, in preferred order. Omitted for free, permit, prohibited and
   * park & ride zones — a money answer would be wrong there, and an empty
   * "Pay now" button on a free lot is worse than no button.
   *
   * SEED DEFAULT ONLY — admin-editable at /admin/map. Read the MERGED store
   * (getParkingZones()), never this array, or Chamber edits will not show.
   */
  pay?: PayHandoff[];
}

export const RULE_LABELS: Record<ParkingRule, string> = {
  "free-2hr": "Free — 2-hour limit",
  "free-unrestricted": "Free — no time limit",
  paid: "Paid",
  "business-customer": "Customer parking — while you're at the business",
  "park-and-ride-24h": "Park & ride — 24 hr max",
  prohibited: "No parking",
  "load-zone": "Loading / dropoff only",
  permit: "Permit holders only",
};

/**
 * `business-customer` (owner request, 2026-08-04): a lot a business keeps for
 * the people visiting it — park while you're in the shop, the café, the salon.
 *
 * It is deliberately NOT `free-unrestricted` with a note. In Kingston the whole
 * problem these lots have is ferry riders leaving a car all day, and the
 * distinction a visitor needs is not "does it cost money" but "am I the person
 * this space is for". Giving it its own rule is what lets the map answer that
 * in one colour, and what lets a business owner see their lot marked as theirs.
 *
 * The nearest neighbours, and why it is neither:
 *   - `permit`  — you must hold something issued in advance; a visitor cannot
 *     qualify on the spot. Here, walking into the shop IS qualifying.
 *   - `free-2hr` — a public space with a clock on it. Here the limit is not
 *     time, it is patronage: five minutes is fine if you are not a customer.
 *
 * Per-lot specifics (which businesses, any posted time cap, whether tow signs
 * are up) belong in the zone's `summary`/`details`, exactly as the free 2-hour
 * row carries "the Port says do NOT use it for ferry travel".
 */

const STUDY_NOTE = "Per 2015 county study — obey posted signs.";
const STUDY_URL =
  "https://portofkingston.org/wp-content/uploads/2022/10/Kingston-Complete-Streets-Transportation-report.pdf";
const PORT_PARKING_URL = "https://portofkingston.org/port-of-kingston-parking/";
const PORT_MAP_URL =
  "https://portofkingston.org/wp-content/uploads/2025/12/Updated-Parking-Map-12-30-25.pdf";
const KITSAP_TRANSIT_PR_URL =
  "https://www.kitsaptransit.com/rider-resources/park-and-ride-lots";

/** Caveat for every polygon georeferenced from the Port's schematic map. */
const PORT_GEO_NOTE =
  "Outline georeferenced from the Port's official 12-30-25 map and aerial imagery (±10 m) — the painted stall markings on the ground always win.";

/** Stronger caveat for the small shapes placed from the schematic alone. */
const PORT_SCHEMATIC_NOTE =
  "Placed from the Port's schematic map only — among the least certain shapes here. Field-check before relying on the outline; signs and stall markings win.";

export const parkingZones: MapZone[] = [
  /* ---------------- Port of Kingston (georeferenced sections) ---------------- */
  // Superseded (July 2, 2026): the original single port-free-2hr polygon sat
  // ~70 m NE of the real row, at the Washington Blvd/SR-104 fork beside
  // Kiwanis Park — the wrong park. The oval below matches the schematic's
  // stadium shape, its position between row 214–233 and Mike Wallace Park,
  // and the ~30-stall count visible on aerial imagery.
  {
    id: "port-free-2hr-row",
    name: "Free 2-hour row (Mike Wallace Park)",
    rule: "free-2hr",
    summary:
      "Free, 2 hours strictly enforced — the Port says do NOT use it for ferry travel. Overstaying means a ticket.",
    details:
      "The stadium-shaped island of back-to-back stalls between paid row 214–233 and Mike Wallace Park's NW corner, clearly visible on aerial imagery as an oval double row (~50 m long). Overstays are a $40 ticket (doubles after 15 days; tow possible). If a ferry delay traps you, call the Port office (360-297-3545) BEFORE the two hours expire.",
    confidence: "probable",
    sourceUrl: PORT_MAP_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "no",
    center: [47.79654, -122.49752],
    polygon: [
      [47.796517, -122.497863],
      [47.796657, -122.497223],
      [47.796563, -122.497177],
      [47.796423, -122.497817],
    ],
  },
  {
    id: "port-pokpark-north-rows",
    name: "POKPARK north rows (181–233 & 201–213)",
    rule: "paid",
    summary:
      "$12/12 hr car · $6 motorcycle · $3.49/hr short-term — text POKPARK to 25023. Spaces 181–190, 201–213, 214–233.",
    details:
      "L-shaped block of numbered rows between lower Washington Blvd and the free 2-hour island: two parallel rows (181–190 and 214–233) running ENE–WSW plus the 201–213 stub along the drive at the NE corner near the Shed and the big white building. Also contains 3 employee stalls and a disabled stall (not broken out). Pay by text (POKPARK to 25023, T2 Mobile Pay), at the Marina Office 8am–5pm, or by card by phone 360-297-3545. Overnight for cars is never explicitly authorized — call the Port office first. No RVs on Port property.",
    confidence: "probable",
    sourceUrl: PORT_PARKING_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "confirm-first",
    pay: [{ vendor: "t2", code: "POKPARK", shortCode: PORT_SHORT_CODE }],
    center: [47.796677, -122.497454],
    polygon: [
      [47.796936, -122.497085],
      [47.796756, -122.496941],
      [47.796726, -122.497024],
      [47.796687, -122.497231],
      [47.79668, -122.497286],
      [47.796425, -122.498005],
      [47.796495, -122.498063],
      [47.796593, -122.497768],
      [47.796647, -122.497811],
      [47.796821, -122.49733],
    ],
  },
  {
    id: "port-pokpark-main-fan",
    name: "POKPARK main lot fan (spaces 1–88)",
    rule: "paid",
    summary:
      "$12/12 hr car · $6 motorcycle · $3.49/hr short-term — text POKPARK to 25023. Spaces 1–88 in the angled rows by the marina.",
    details:
      "The fan of angled double rows in the SW half of the marina lot (rows 19–31/32–46/47–66/67–88, 5–10/11–18, 1–4), 2–3 min walk to the ferry. Polygon includes the internal drive aisles between rows (deliberate merge); its SE edge approximates the boundary where marina-tenant permit stalls take over at the row ends. Same payment and overnight rules as all numbered spaces: text POKPARK to 25023, and call the Port office (360-297-3545) before leaving a car overnight. Monthly commuter permit $139.99 (limited; daily use, not storage).",
    confidence: "probable",
    sourceUrl: PORT_PARKING_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "confirm-first",
    pay: [{ vendor: "t2", code: "POKPARK", shortCode: PORT_SHORT_CODE }],
    center: [47.796658, -122.498459],
    polygon: [
      [47.797102, -122.498579],
      [47.796665, -122.4982],
      [47.796382, -122.498085],
      [47.796307, -122.498163],
      [47.79649, -122.498455],
      [47.79652, -122.498969],
      [47.797142, -122.498764],
    ],
  },
  {
    id: "port-pokpark-89-103",
    name: "POKPARK row 89–103",
    rule: "paid",
    summary:
      "$12/12 hr car · $6 motorcycle · $3.49/hr short-term — text POKPARK to 25023. A single row along the drive NW of the yacht club.",
    details:
      "Short numbered row (89–103) lining the loop drive northwest of the Kingston Cove Yacht Club, immediately west of the KCYC-permit-only row. Same rates, payment and overnight rules as the rest of POKPARK (call 360-297-3545 before overnight).",
    confidence: "probable",
    sourceUrl: PORT_PARKING_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "confirm-first",
    pay: [{ vendor: "t2", code: "POKPARK", shortCode: PORT_SHORT_CODE }],
    center: [47.797108, -122.498495],
    polygon: [
      [47.797247, -122.49855],
      [47.797, -122.49835],
      [47.79697, -122.49844],
      [47.797214, -122.498641],
    ],
  },
  {
    id: "port-pokhill",
    name: "POKHILL hill zone (104–162)",
    rule: "paid",
    summary:
      "$12/12 hr car · $6 motorcycle · $15 truck+trailer ($30/24 hr) · $3.49/hr short-term — text POKHILL to 25023. Spaces 104–132 plus truck/trailer overflow 133–162 on the slope.",
    details:
      "The long double-loaded strip west of the boat-launch access road, running from NE West Kingston Rd downhill to the main lot (~120 m). Spaces 104–132 are general parking; 133–162 are truck-and-trailer overflow for busy launch days. A few Port-use stalls sit at the very top end. Same text-to-pay system (POKHILL to 25023) and overnight rule of thumb: call the Port office first (360-297-3545).",
    confidence: "probable",
    sourceUrl: PORT_PARKING_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "confirm-first",
    pay: [{ vendor: "t2", code: "POKHILL", shortCode: PORT_SHORT_CODE }],
    center: [47.797685, -122.498838],
    polygon: [
      [47.79824, -122.49903],
      [47.79824, -122.49874],
      [47.79713, -122.49864],
      [47.79713, -122.49894],
    ],
  },
  {
    id: "port-poktt",
    name: "POKTT truck & trailer zone (301–318)",
    rule: "paid",
    summary:
      "Trucks with boat trailers ONLY — $15/12 hr or $30/24 hr, text POKTT to 25023. Spaces 301–318 by the boat launch.",
    details:
      "The westernmost band of the main lot fan, next to the launch approach drive — 18 long angled stalls (trailers clearly visible on aerial imagery). Regular cars may not park here. Trailers may not be dropped without the truck attached; unattended boats on trailers need Port approval. Disabled stalls sit at the SW (launch) end of the band. Multi-day: coordinate with the Port office (360-297-3545).",
    confidence: "probable",
    sourceUrl: PORT_PARKING_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "confirm-first",
    pay: [{ vendor: "t2", code: "POKTT", shortCode: PORT_SHORT_CODE }],
    center: [47.79682, -122.49901],
    polygon: [
      [47.79712, -122.49897],
      [47.79706, -122.49873],
      [47.79652, -122.49905],
      [47.79658, -122.49929],
    ],
  },
  {
    id: "port-15min-dropoff",
    name: "15-minute dropoff (Mike Wallace Park edge)",
    rule: "load-zone",
    summary:
      "15-minute dropoff/loading only — on the drive along Mike Wallace Park's west edge, east of the free 2-hour row.",
    details:
      "Hatched dropoff stalls on the short drive between the free 2-hour island's east end and Mike Wallace Park's NW boundary, with disabled stalls just SE of them along the park edge (disabled stalls not polygonized). A small feature placed from the schematic only — the least certain placement in this set; field-check recommended.",
    confidence: "probable",
    sourceUrl: PORT_MAP_URL,
    sourceNote: PORT_SCHEMATIC_NOTE,
    overnight: "no",
    center: [47.79646, -122.49716],
    polygon: [
      [47.79653, -122.49719],
      [47.7965, -122.49706],
      [47.79639, -122.49713],
      [47.79642, -122.49726],
    ],
  },
  {
    id: "port-kcyc-permit-row",
    name: "KCYC permit-only row",
    rule: "permit",
    summary:
      "Kingston Cove Yacht Club permit holders only — row along the drive just NW of the clubhouse.",
    details:
      "Marked 'KCYC PERMIT ONLY' on the Port map, between public row 89–103 and the KCYC clubhouse. Not available to visitors; enforcement is the Port's standard $40–50 ticket schedule.",
    confidence: "probable",
    sourceUrl: PORT_MAP_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "confirm-first",
    center: [47.796802, -122.498228],
    polygon: [
      [47.796915, -122.498263],
      [47.796721, -122.498108],
      [47.79669, -122.498193],
      [47.796884, -122.498349],
    ],
  },
  {
    id: "port-tenant-row-park",
    name: "Marina tenant row (by promenade restrooms)",
    rule: "permit",
    summary:
      "Marina tenant permit required — row between the free 2-hour island and the waterfront promenade restrooms.",
    details:
      "Purple 'MARINA TENANT PARKING (PERMIT REQUIRED)' row on the Port map, running WSW from below the dropoff/disabled area toward the promenade restrooms inside the D-shaped loop pod. Visitors may not park here; moorage tenants use their permit.",
    confidence: "probable",
    sourceUrl: PORT_MAP_URL,
    sourceNote: PORT_SCHEMATIC_NOTE,
    overnight: "confirm-first",
    center: [47.796262, -122.497716],
    polygon: [
      [47.796337, -122.497585],
      [47.796295, -122.497551],
      [47.796187, -122.497848],
      [47.796229, -122.497882],
    ],
  },
  {
    id: "port-tenant-fan-block",
    name: "Marina tenant block (fan row ends)",
    rule: "permit",
    summary:
      "Marina tenant permit required — the largest tenant block, at the SE (waterfront) end of fan rows 5–18.",
    details:
      "The biggest of the purple tenant areas in the main fan, at the waterfront end of the 5–10/11–18 row. Smaller tenant caps also exist at the SE ends of rows 19–88 and 1–4 (not polygonized separately — they fall just outside the POKPARK fan polygon's SE cut).",
    confidence: "probable",
    sourceUrl: PORT_MAP_URL,
    sourceNote: PORT_SCHEMATIC_NOTE,
    overnight: "confirm-first",
    center: [47.796326, -122.498538],
    polygon: [
      [47.796474, -122.498527],
      [47.796419, -122.498367],
      [47.79618, -122.498543],
      [47.796231, -122.498714],
    ],
  },
  {
    id: "port-boat-launch-apron",
    name: "Boat launch apron",
    rule: "prohibited",
    summary:
      "Launch ramp maneuvering apron — no parking. Launch restrooms sit at its center; ramp at the SW corner.",
    details:
      "Paved maneuvering area between the hill-zone drive, the POKTT band and the launch ramp (ramp at ~47.7963, -122.4994). Keep clear for backing trailers; parked vehicles here block the ramp. Trucks with trailers belong in POKTT (301–318) or hill overflow (133–162).",
    confidence: "probable",
    sourceUrl: PORT_MAP_URL,
    sourceNote: PORT_GEO_NOTE,
    overnight: "no",
    center: [47.796418, -122.499288],
    polygon: [
      [47.79656, -122.49928],
      [47.79647, -122.49903],
      [47.79636, -122.49917],
      [47.7963, -122.49947],
      [47.7964, -122.49949],
    ],
  },
  /* ---------------- Diamond / WSDOT lot ---------------- */
  {
    id: "diamond-d515",
    name: "Diamond lot D515 (WSDOT commuter lot)",
    rule: "paid",
    summary:
      "$8 for 0–12 hr, $12 for 12–24 hr — overnight OK. At NE 1st St & Ohio Ave, one block from the ferry. Free with a disabled placard.",
    details:
      "The WSDOT-owned, Diamond-operated lot at 26613 Ohio Ave NE — the angled strip on NE 1st St between Ohio and Iowa, a 5-minute walk to the tollbooths. Overnight and multi-day parking allowed (WSF publishes rates from 2 days $24 up to 7 days $38). Monthly permit $122.70 all-in via Diamond PermitPoint, valid 24/7. Pay at the kiosk (card) or with PayByPhone / ParkMobile. Vehicles with a valid disabled placard or plate park free — this lot only. Questions: Diamond Parking, 206-729-0590.",
    confidence: "verified",
    sourceUrl:
      "https://wsdot.com/ferries/vesselwatch/terminaldetail.aspx?terminalid=12",
    overnight: "yes",
    pay: [
      { vendor: "parkmobile", code: "97599515", label: "Pay with ParkMobile" },
      { vendor: "paybyphone", code: "", label: "Pay with PayByPhone" },
    ],
    center: [47.798685, -122.496815],
    // NO POLYGON ON PURPOSE. The four corners that used to sit here described a
    // 98 m × 0.21 m sliver — 21 m² of area for a 73-stall lot that needs ~1,900 m².
    // Two of the corners were near-duplicates, so it drew as a hairline streaked
    // across the other zones rather than as a lot. OpenStreetMap has no footprint
    // for D515 either (its nearest mapped lot is a private customers-only lot 58 m
    // away), so there is nothing to replace it with that we could source. A circle
    // at the verified center claims only what we actually know; re-adding a shape
    // is a job for /admin/maps with aerial imagery under it.
  },

  /* ---------------- Park & rides ---------------- */
  {
    id: "georges-corner-pr",
    name: "George's Corner Park & Ride",
    rule: "park-and-ride-24h",
    summary:
      "Free, large lot, max 24 hours. SR 104 × Hansville Rd, ~2.5 mi from the dock; buses 307 & 391 run to the ferry.",
    details:
      "Kitsap Transit lot at 27618 Hansville Rd NE: free, paved, lit, with a shelter, bike racks/lockers and 4 free EV chargers. Kitsap Transit's posted rule: park & rides are intended for day use and parking is limited to no more than 24 hours — so it works for a day trip, but not for multi-day ferry parking. Routes 307 (Kingston/North Viking Fast Ferry Express) and 391 (Kingston/Bainbridge) connect to the dock.",
    confidence: "verified",
    sourceUrl: KITSAP_TRANSIT_PR_URL,
    overnight: "no",
    center: [47.81256, -122.53962],
  },
  {
    id: "bayside-pr",
    name: "Bayside Community Church Park & Ride",
    rule: "park-and-ride-24h",
    summary:
      "Free, max 24 hours. Barber Cut Off Rd, ~0.8 mi west of downtown; buses 302 & 391.",
    details:
      "Church lot at 25992 Barber Cut Off Rd NE shared as an official Kitsap Transit park & ride — the only church lot in Kingston with a documented ferry-commuter arrangement. Free, paved, lit; same Kitsap Transit rule: day use, no more than 24 hours. Served by Routes 302 and 391.",
    confidence: "verified",
    sourceUrl: KITSAP_TRANSIT_PR_URL,
    sourceNote:
      "Lot rules verified with Kitsap Transit; pin placement should be double-checked against aerial imagery before print use.",
    overnight: "no",
    center: [47.7987, -122.50823],
  },

  /* ---------------- 2-hour streets (2015 county study) ---------------- */
  {
    id: "street-ne-1st",
    name: "NE 1st St (Ohio–Iowa)",
    rule: "free-2hr",
    summary: "Free on-street parking, posted 2-hour limit in the downtown core.",
    details:
      "The county's downtown parking inventory shows a posted 2-hour limit here, meant to keep spaces turning over for shop customers. Posted hours of the limit aren't documented online — read the sign on the pole; it is the legal authority.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "no",
    center: [47.79862, -122.49724],
    // The county study's 2-hour stretch of NE 1st per the OSM-derived overlay
    // (slightly longer than the Ohio–Iowa block the name focuses on).
    streetPaths: [
      [[47.79755, -122.49563], [47.7976, -122.4957], [47.79766, -122.49578], [47.79782, -122.49603], [47.79786, -122.49608], [47.79816, -122.49654], [47.79843, -122.49695], [47.79881, -122.49753], [47.79932, -122.49824], [47.79937, -122.49827], [47.7994, -122.49829], [47.79944, -122.49832], [47.79963, -122.49839]],
    ],
  },
  {
    id: "street-ohio-ave",
    name: "Ohio Ave NE (NE 1st–NE 2nd)",
    rule: "free-2hr",
    summary: "Free on-street parking, posted 2-hour limit.",
    details:
      "2-hour limit per the county parking inventory. Free; check the posted sign for the hours the limit applies.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "no",
    center: [47.79965, -122.49525],
    streetPaths: [
      [[47.79816, -122.49654], [47.79823, -122.49644], [47.79834, -122.49628], [47.79847, -122.4961]],
    ],
  },
  {
    id: "street-iowa-ave",
    name: "Iowa Ave NE (SR 104–NE 3rd)",
    rule: "free-2hr",
    summary: "Free on-street parking, posted 2-hour limit.",
    details:
      "2-hour limit per the county parking inventory. Free; check the posted sign for the hours the limit applies.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "no",
    center: [47.7995, -122.4965],
    streetPaths: [
      [[47.80049, -122.49519], [47.80023, -122.49552], [47.79952, -122.4965], [47.79912, -122.4971], [47.799, -122.49727], [47.79889, -122.49742], [47.79881, -122.49753], [47.79875, -122.49761], [47.79868, -122.49772], [47.79855, -122.49794], [47.79853, -122.49796], [47.79849, -122.49805]],
    ],
  },
  {
    id: "street-ne-2nd",
    name: "NE 2nd St (Iowa–Washington)",
    rule: "free-2hr",
    summary: "Free on-street parking, posted 2-hour limit.",
    details:
      "2-hour limit per the county parking inventory. Free; check the posted sign for the hours the limit applies.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "no",
    center: [47.79981, -122.49709],
    streetPaths: [
      [[47.80068, -122.499], [47.8007, -122.49892], [47.80071, -122.49886], [47.80073, -122.4987], [47.80072, -122.49842], [47.80069, -122.49834], [47.80055, -122.49805], [47.80018, -122.49754], [47.80013, -122.49745], [47.79992, -122.49712], [47.79952, -122.4965], [47.79892, -122.49561], [47.79887, -122.49552], [47.79883, -122.49546], [47.79881, -122.49543], [47.79856, -122.49505], [47.79826, -122.4946]],
    ],
  },
  {
    id: "street-illinois-ave",
    name: "Illinois Ave NE (mixed)",
    rule: "free-2hr",
    summary:
      "2-hour limit on the lower blocks near SR 104; unrestricted on the upper blocks toward NE 3rd/4th.",
    details:
      "The county inventory shows a split: time-restricted (2-hour) close to SR 104, unrestricted free parking farther up the hill. The block-by-block boundary is only as current as the 2015 survey — go by the signs.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "no",
    center: [47.8008, -122.49649],
    // The 2-hour LOWER blocks only (this zone's rule); the unrestricted upper
    // blocks the summary mentions are a different stretch with no zone entry.
    streetPaths: [
      [[47.79963, -122.49839], [47.79968, -122.49826], [47.7997, -122.49824], [47.80018, -122.49754]],
    ],
  },

  /* ---------------- Unrestricted streets ---------------- */
  {
    id: "street-georgia-ave",
    name: "NE Georgia Ave",
    rule: "free-unrestricted",
    summary:
      "Free, no time limit — the closest truly unlimited street parking to the ferry (with Pennsylvania Ave).",
    details:
      "Inventoried as unrestricted — part of ~90 unrestricted on-street spaces downtown that sat only ~30% full even at peak. Overnight is lawful where no sign restricts it, but a vehicle left in the right-of-way more than 24 hours can be tagged as apparently abandoned and impounded (RCW 46.55.085) — park overnight, don't store.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "yes",
    center: [47.801539, -122.499129],
    streetPaths: [
      [[47.80154, -122.49837], [47.80154, -122.49989]],
    ],
  },
  {
    id: "street-pennsylvania-ave",
    name: "Pennsylvania Ave NE (one side only)",
    rule: "free-unrestricted",
    summary:
      "Free, no time limit — but on ONE SIDE of the street only. The other side is no-parking.",
    details:
      "The county inventory shows unrestricted parking on one side of Pennsylvania Ave only, with the opposite side (and the stretch near Central Ave) marked no-parking. Same overnight rule as Georgia Ave: lawful where unsigned, but 24+ hours risks abandoned-vehicle tagging under RCW 46.55.085.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "yes",
    center: [47.801407, -122.497531],
    // NO curb on purpose: the county study says ONE side only but never names
    // the side, so the map draws the centre line and the words carry the caveat.
    streetPaths: [
      [[47.80072, -122.49842], [47.80077, -122.49839], [47.80089, -122.49831], [47.80139, -122.49759], [47.80157, -122.49733], [47.80177, -122.49704], [47.80198, -122.49672], [47.80216, -122.49645]],
    ],
  },

  /* ---------------- Prohibited streets ---------------- */
  {
    id: "street-central-ave",
    name: "Central Ave NE",
    rule: "prohibited",
    summary: "No parking along essentially the whole street (bike lanes).",
    details:
      "The main outbound route from the Port to SR 104 — marked prohibited for parking in the county inventory, and it carries bike lanes. Don't park here.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "no",
    center: [47.7997, -122.49836],
    // Two stretches: OSM has no rule-tagged ways for the middle block, so the
    // gap stays a gap rather than being bridged (see header honesty note).
    streetPaths: [
      [[47.79676, -122.4979], [47.79679, -122.49796], [47.7968, -122.49797], [47.79699, -122.4981], [47.79736, -122.49838], [47.79754, -122.49848], [47.7976, -122.4985], [47.79765, -122.4985], [47.79768, -122.49851], [47.79773, -122.49851], [47.79817, -122.4985], [47.79826, -122.49849], [47.79838, -122.49849], [47.79844, -122.49849]],
      [[47.80089, -122.49831], [47.80092, -122.49834], [47.80095, -122.49836], [47.80099, -122.49837], [47.80102, -122.49838], [47.80106, -122.49838], [47.80121, -122.49838], [47.80154, -122.49837], [47.80161, -122.49837], [47.80166, -122.49837], [47.8019, -122.49837], [47.80248, -122.49837], [47.80253, -122.49836], [47.80258, -122.49835], [47.80262, -122.49834]],
    ],
  },
  {
    id: "street-washington-blvd",
    name: "Washington Blvd NE (north of the SR 104 loop)",
    rule: "prohibited",
    summary: "No parking on the ferry offload stretch north of the SR 104 loop.",
    details:
      "Marked prohibited in the county inventory. SR 104 outside the downtown core and NE West Kingston Rd are also no-parking, and much of the eastbound SR 104 shoulder is striped/signed against ferry-queue parking. NOTE: this entry no longer covers the block between the two SR 104 legs — that block has 2-hour parking on both sides and is listed separately.",
    confidence: "probable",
    sourceUrl: STUDY_URL,
    sourceNote: STUDY_NOTE,
    overnight: "no",
    center: [47.79855, -122.49419],
    // Only the offload stretch north/east of the SR 104 loop, matching the
    // entry's own carve-out: the loop block (2-hr, both sides) is its own zone
    // below, and the short marina-side stretch below the west junction is not
    // claimed here. Two chains — OSM has no node joining them at the Iowa fork.
    streetPaths: [
      [[47.79985, -122.49278], [47.79993, -122.49262], [47.79998, -122.49252], [47.80004, -122.49243], [47.80011, -122.49235], [47.80026, -122.49221], [47.8004, -122.49212], [47.80053, -122.492], [47.80067, -122.49189], [47.80086, -122.49177], [47.80101, -122.49156], [47.80124, -122.49122], [47.80136, -122.49113], [47.80148, -122.49097], [47.80158, -122.49083], [47.80166, -122.49077], [47.80176, -122.49063], [47.80191, -122.49039], [47.80199, -122.4902], [47.80208, -122.49003], [47.80221, -122.48977], [47.80228, -122.48964], [47.80235, -122.48952], [47.80256, -122.48914], [47.80267, -122.48896], [47.80278, -122.48879], [47.80302, -122.48849], [47.80311, -122.48843], [47.80323, -122.48837], [47.80332, -122.4883], [47.80341, -122.48821], [47.80349, -122.48806], [47.80355, -122.48791], [47.80363, -122.48778], [47.80377, -122.48768], [47.80386, -122.48758], [47.80394, -122.48742], [47.80404, -122.48719], [47.80408, -122.48712], [47.80414, -122.48705], [47.80451, -122.48685], [47.80526, -122.48639], [47.80538, -122.48628], [47.80548, -122.48618], [47.80556, -122.48614], [47.80565, -122.48612], [47.80579, -122.48603], [47.80599, -122.4859], [47.80615, -122.48576], [47.80622, -122.48572], [47.80629, -122.4857], [47.80638, -122.4857], [47.80643, -122.4857], [47.80669, -122.48572], [47.80679, -122.4857], [47.80688, -122.48565], [47.80706, -122.48553], [47.80721, -122.48537], [47.80735, -122.48519], [47.80746, -122.48496]],
      [[47.79945, -122.49315], [47.79938, -122.49319], [47.79931, -122.49324], [47.79923, -122.4933], [47.79916, -122.49338], [47.79902, -122.49353], [47.79895, -122.49362], [47.7989, -122.49367], [47.79887, -122.4937], [47.79885, -122.49374], [47.79883, -122.49378], [47.7988, -122.49383], [47.79868, -122.49401], [47.79856, -122.49419], [47.79841, -122.49438], [47.79831, -122.49452], [47.79826, -122.4946], [47.79791, -122.49511], [47.79755, -122.49563]],
    ],
  },
  {
    // Chamber field correction, July 2026. The 2015 county inventory marked the
    // WHOLE of Washington Blvd NE as no-parking, so the app was telling visitors
    // they could not park on a block where they can — the costliest direction for
    // this error to point. The offload-route entry above now stops short of here.
    //
    // Extent from OpenStreetMap: the ~114 m of Washington Blvd NE bounded by an
    // SR 104 junction at each end — [47.797036, -122.496929] on the west and
    // [47.797548, -122.495625] on the east (OSM ways 292111730 + 117576626).
    // The block is signed one-way for ferry offload AND has parking both sides;
    // the old entry conflated "one-way offload route" with "no parking".
    //
    // E31 phase 6: MapZone now carries street polylines + a curb side, so this
    // block finally draws what the field check found — a stroke hugging EACH
    // curb (curb: "both" is the only seeded curb value, because this is the
    // only zone whose source names the side).
    id: "street-washington-blvd-104-loop",
    name: "Washington Blvd NE (between the SR 104 legs)",
    rule: "free-2hr",
    summary:
      "Free 2-hour parking on BOTH sides, on the block between the two SR 104 legs. One-way for ferry offload — but you may park.",
    details:
      "The short block of Washington Blvd NE enclosed by the SR 104 loop, a block up from the dock. Free parking with a posted 2-hour limit on both sides of the street. The street is one-way here because it carries traffic coming off the boat, which is why an earlier version of this map wrongly showed the whole street as no-parking. Obey the posted signs — they are the legal authority.",
    confidence: "probable",
    sourceNote:
      "Chamber field correction July 2026, replacing the 2015 county study — obey posted signs.",
    overnight: "no",
    center: [47.797292, -122.496277],
    // OSM ways 292111730 + 117576626 between the two SR 104 junctions — the
    // exact extent PR #78 documented.
    streetPaths: [
      [[47.79704, -122.49693], [47.79707, -122.49683], [47.79731, -122.49606], [47.79734, -122.49598], [47.79736, -122.49592], [47.79746, -122.49574], [47.79748, -122.49572], [47.79755, -122.49563]],
    ],
    curb: "both",
  },

  /* ---------------- Unverified — field-check before relying on these ---------------- */
  {
    id: "washington-blvd-lot",
    name: "Washington Blvd lot (32 spaces) — unverified",
    rule: "paid",
    summary:
      "UNVERIFIED — the 2016 county study lists a 32-space public pay lot between Main St and NE 1st; its current operator and payment status are unknown.",
    details:
      "The grass/gravel triangle at roughly 11420 NE 1st St, between NE 1st St, Ohio Ave and Washington Blvd. Listed as the smallest public pay lot in the 2016 study, but nothing current confirms who runs it or how (or whether) you pay in 2026. Field-check before counting on it.",
    confidence: "unverified",
    sourceUrl: STUDY_URL,
    sourceNote: "Unverified — needs an on-the-ground check before you rely on it.",
    overnight: "confirm-first",
    center: [47.798077, -122.496023],
  },
  {
    id: "sr104-wedge-lot",
    name: "Small 2-hour lot at SR 104 / NE 1st split — unverified",
    rule: "free-2hr",
    summary:
      "UNVERIFIED — OpenStreetMap tags a small public lot here with a 2-hour max stay; the only source is the map tag.",
    details:
      "A small lot in the wedge west of NE 1st St where it splits from SR 104, behind the buildings near Iowa Ave. OSM says public access with a 2-hour limit, but no official source confirms it. Verify the signage on the ground before treating it as public parking.",
    confidence: "unverified",
    sourceUrl: "https://www.openstreetmap.org/way/118260727",
    sourceNote: "Unverified — needs an on-the-ground check before you rely on it.",
    overnight: "no",
    center: [47.799109, -122.498188],
  },
];

